[default]
extend-ignore-re = [
    "systemd-localed",
]

[default.extend-identifiers]
WRONLY = "WRONLY"

[default.extend-words]
datas = "datas"
arange = "arange"
localed = "localed"
WRONLY = "WRONLY"
utput = "utput"
